// ==UserScript==
// @ScriptName        影视App公告去弹窗[验证版]
// @Description       影视App"官方公告"置顶弹窗去除（纯明文HTTP，无需MITM）
// @UpdateTime        2026-09-26
// ==/UserScript==

# > 公告弹窗：is_top=1 时清空 data（HTTP明文，不加 MITM hostname）
^http:\/\/23\.225\.14\.70:520\/nmtq\.php\/v\d\/logs url jsonjq-response-body 'if .data.is_top then .data = [] else . end'
