// ==UserScript==
// @ScriptName        汽水音乐去开屏[验证版]
// @Description       汽水音乐开屏广告-穿山甲SDK精确域名拦截（本地验证版）
// @UpdateTime        2026-09-26
// ==/UserScript==

hostname = api-access.pangolin-sdk-toutiao.com, api-access.pangolin-sdk-toutiao1.com, log-api.pangolin-sdk-toutiao.com, vas-lf-x.snssdk.com, *.pglstatp-toutiao.com, *.bytescm.com

# > 穿山甲广告SDK（开屏/激励视频广告源）
^https?:\/\/api-access\.pangolin-sdk-toutiao\.com\/ url reject-200
^https?:\/\/api-access\.pangolin-sdk-toutiao1\.com\/ url reject-200
^https?:\/\/log-api\.pangolin-sdk-toutiao\.com\/ url reject-200
^https?:\/\/vas-lf-x\.snssdk\.com\/video\/ url reject-200
^https?:\/\/sf[0-9]*-fe-tos\.pglstatp-toutiao\.com\/ url reject-200
^https?:\/\/lf-cdn-tos\.bytescm\.com\/obj\/static\/ad\/ url reject-200
